---
title: "Recalculation of p values and fold change using DESeq2"
author: "xyz"
date: "2020/11/21"
output: html_document
---

```{r Public DB}
library(DESeq2)
library(ggplot2)
library(dplyr)
library(xlsx)

df <- readRDS("../temp/ncbiMasterProtein.rds")

abundance <- df[, 48:55]
abundance[is.na(abundance)] <- 0
#abundance<-prop.table(as.matrix(abundance),2)
abundance <- data.frame(
  high1 = abundance[, 1] + abundance[, 2],
  high2 = abundance[, 3] + abundance[, 4],
  low1 = abundance[, 5] + abundance[, 6],
  low2 = abundance[, 7] + abundance[, 8]
)
row.names(abundance) <- df$Accession
abundance <- abundance[rowSums(abundance) > 0,]

# #### t test ####
#
# data1 <- t(abundance)
# data1 <-
#   data.frame(
#     Treatments = c("High", "High", "Low", "Low"),
#     data1,
#     stringsAsFactors = F
#   )
# data1$Treatments <- as.factor(data1$Treatments)
#
#
# diff1 <- data1 %>%
#   select_if(is.numeric) %>%
#   map_df(~ broom::tidy(t.test(. ~ Treatments, data = data1)), .id = 'var')
#
# diff1$q.value <- p.adjust(diff1$p.value, "BH")
# diff1.filter <- diff1 %>% filter(q.value < 0.05)
#
# #### use limma ####
#
# library(limma)
# design <- model.matrix( ~ 0 + factor(c("High", "High", "Low", "Low")))
# colnames(design) <- levels(factor(c("High", "High", "Low", "Low")))
# rownames(design) <- colnames(abundance)
# contrast.matrix <-
#   makeContrasts(paste0(unique(c(
#     "High", "High", "Low", "Low"
#   )), collapse = "-"), levels = design)
# fit <- lmFit(abundance, design)
# fit2 <- contrasts.fit(fit, contrast.matrix)
# fit2 <- eBayes(fit2)
# tempOutput <- topTable(fit2, coef = 1, n = Inf)
# nrDEG <- na.omit(tempOutput)

####  use DESeq2 ####

coldata <- data.frame(row.names = colnames(abundance),
                      condition = factor(c("High", "High", "Low", "Low")))
abundance <- apply(abundance, 2, function(x)
  round(x, 0))
dds <- DESeqDataSetFromMatrix(countData = abundance,
                              colData = coldata,
                              design =  ~ condition)
dds2 <- DESeq(dds, fitType = 'local')
DEGs <- results(dds2)
DEGsDf <- na.exclude(as.data.frame(DEGs))
saveRDS(DEGsDf,
        "../temp/low vs high Public DB differentially expressed proteins.rds")
write.xlsx2(DEGsDf,
            "../table/low vs high Public DB differentially expressed proteins.xlsx")
DEGsDf <-
  readRDS("../temp/low vs high Public DB differentially expressed proteins.rds")


# The Standard of significance was fold change >= 2 or =< 1/2 (log(DEGsDlog2FoldChangef)>=1 or <=-1),
# adjusted P value =< 0.05

judgeSignificance <- function(x, y) {
  if (x <= 0.05) {
    if (y <= -1)
      return ("down")
    else if (y >= 1)
      return ("up")
    else
      return ("no")
  }
  else
    return("no")
}

drawVolcanoPlot <- function(df, fileName) {
  colnames(df) <- c("FDR", "FC")
  df$size <- -log10(df$FDR)
  df <-
    cbind(df, significance = factor(mapply(judgeSignificance, df$FDR, df$FC)))
  ggplot(df, aes(FC, -1 * log10(FDR))) +
    geom_point(
      aes(
        fill = significance,
        colour = significance,
        size = size
      ),
      shape = 21,
      alpha = 0.6
    ) +
    # Resize the point from 0.1 to 10
    scale_size(range = c(.1, 10)) +
    theme(text = element_text(size = 30)) +
    guides(
      fill = guide_legend(override.aes = list(size = 10)),
      size = FALSE,
      colour = FALSE
    ) +
    scale_fill_discrete(labels = paste(levels(df$significance), table(df$significance))) +
    labs(x = expression(log[2](FC)), y = expression(-log[10](FDR))) +
    geom_hline(yintercept = -log10(0.05), linetype = 4) +
    # Limit the scope of the drawing and add linear coordinates
    scale_y_continuous(limits = c(0, 60), breaks = c(1.3, 10, 20, 40)) +
    geom_vline(xintercept = c(-log2(2), log2(2)), linetype = 4) +
    # Limit the scope of the drawing, make it left-right symmetric, and add linear coordinates
    scale_x_continuous(limits = c(-31, 31), breaks = sort(c(seq(
      -30,
      30, length.out = 6
    ),-1, 1))) +
    ggsave(fileName,
           width = 10.24,
           height = 7.68,
           dpi = 100)
}

drawVolcanoPlot(DEGsDf[, c("padj", "log2FoldChange")], "../figure/low vs high Public DB volcanoPlot.png")
```


```{r Meta DB}
df2 <- readRDS("../temp/metaMasterProtein.rds")
abundance <- df2[, 53:60]
abundance[is.na(abundance)] <- 0
#abundance<-prop.table(as.matrix(abundance),2)
abundance <- data.frame(
  high1 = abundance[, 1] + abundance[, 2],
  high2 = abundance[, 3] + abundance[, 4],
  low1 = abundance[, 5] + abundance[, 6],
  low2 = abundance[, 7] + abundance[, 8]
)
row.names(abundance) <- df2$Accession
abundance <- abundance[rowSums(abundance) > 0,]

coldata <- data.frame(row.names = colnames(abundance),
                      condition = factor(c("High", "High", "Low", "Low")))
abundance <- apply(abundance, 2, function(x)
  round(x, 0))
dds <- DESeqDataSetFromMatrix(countData = abundance,
                              colData = coldata,
                              design =  ~ condition)
dds2 <- DESeq(dds, fitType = 'local')
DEGs <- results(dds2)
DEGsDf <- na.exclude(as.data.frame(DEGs))
saveRDS(DEGsDf,
        "../temp/low vs high Meta DB differentially expressed proteins.rds")
write.xlsx2(DEGsDf,
            "../table/low vs high Meta DB differentially expressed proteins.xlsx")
DEGsDf <-
  readRDS("../temp/low vs high Meta DB differentially expressed proteins.rds")
drawVolcanoPlot <- function(df, fileName) {
  colnames(df) <- c("FDR", "FC")
  df$size <- -log10(df$FDR)
  df <-
    cbind(df, significance = factor(mapply(judgeSignificance, df$FDR, df$FC)))
  ggplot(df, aes(FC,-1 * log10(FDR))) +
    geom_point(
      aes(
        fill = significance,
        colour = significance,
        size = size
      ),
      shape = 21,
      alpha = 0.6
    ) +
    # Resize the point from 0.1 to 10
    scale_size(range = c(.1, 10)) +
    theme(text = element_text(size = 30)) +
    guides(
      fill = guide_legend(override.aes = list(size = 10)),
      size = FALSE,
      colour = FALSE
    ) +
    scale_fill_discrete(labels = paste(levels(df$significance), table(df$significance))) +
    labs(x = expression(log[2](FC)), y = expression(-log[10](FDR))) +
    geom_hline(yintercept = -log10(0.05), linetype = 4) +
    # Limit the scope of the drawing and add linear coordinates
    scale_y_continuous(limits = c(0, 46), breaks = c(1.3, 10, 20, 40)) +
    geom_vline(xintercept = c(-log2(2), log2(2)), linetype = 4) +
    # Limit the scope of the drawing, make it left-right symmetric, and add linear coordinates
    scale_x_continuous(limits = c(-31, 31), breaks = sort(c(seq(
      -30,
      30, length.out = 6
    ), -1, 1))) +
    ggsave(fileName,
           width = 10.24,
           height = 7.68,
           dpi = 100)
}

drawVolcanoPlot(DEGsDf[, c("padj", "log2FoldChange")], "../figure/low vs high Meta DB volcanoPlot.png")
```

